app/models/user.py
from datetime import datetime
from ..extensions import db
from werkzeug.security import generate_password_hash, check_password_hash
from sqlalchemy.orm import validates

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    @validates('username')
    def validate_username(self, key, username):
        if not username:
            raise ValueError('Username is required.')
        if len(username) > 50:
            raise ValueError('Username must be less than or equal to 50 characters.')
        return username

    @validates('email')
    def validate_email(self, key, email):
        if not email:
            raise ValueError('Email is required.')
        if len(email) > 120:
            raise ValueError('Email must be less than or equal to 120 characters.')
        return email

    @validates('password_hash')
    def validate_password_hash(self, key, password):
        if not password:
            raise ValueError('Password is required.')
        if len(password) < 8:
            raise ValueError('Password must be at least 8 characters long.')
        return generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

app/__init__.py
from flask import Flask
from config import Config
from .api import MovieAPI

def create_app():
    from .extensions import jwt, db

    app = Flask(__name__, static_url_path='/static')

    app.config.from_object(Config())

    app.movieapi = MovieAPI(app.config['MOVIEAPI_KEY'])

    jwt.init_app(app)
    db.init_app(app)

    from .main import main as main_blueprint
    from .auth import auth as auth_blueprint
    
    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint)

    with app.app_context():
        db.create_all()
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

# routes
from .routes import *

app/main/routes.py
from . import main

from flask import render_template, redirect,url_for, current_app

@main.route('/')
def index():
    now_playing = current_app.movieapi.get_now_playing()
    popular= current_app.movieapi.get_popular()
    top_rated = current_app.movieapi.get_top_rated()
    upcoming = current_app.movieapi.get_upcoming()

    context = {
        'now_playing': now_playing[0:5],
        'popular': popular[5:10],
        'top_rated': top_rated[0:5],
        'upcoming': upcoming[5:15]
    }
    return render_template('index.html', **context)

@main.route('/movie/<int:movie_id>')
def movie(movie_id:int):
    movie = current_app.movieapi.get_movie_details(movie_id)
    video_key= current_app.movieapi.get_video_id(movie_id)
    similar = current_app.movieapi.get_similar_movies(movie_id)
    images= current_app.movieapi.get_movie_images(movie_id)

    context = {
        'movie': movie,
        'video_key': video_key,
        'similar': similar[0:5],
        'images': images
    }
    return render_template('main/movie.html', **context)

@main.route('/movies/<string:list_type>')
def movie_list(list_type:str):
    from flask import request
    page=request.args.get('page', 1, type=int)

    if list_type == 'now_playing':
        movies = current_app.movieapi.get_now_playing(page)
        title = 'Now Playing'
    elif list_type == 'popular':
        movies = current_app.movieapi.get_popular(page)
        title = 'Popular'
    elif list_type == 'top_rated':
        movies = current_app.movieapi.get_top_rated(page)
        title = 'Top Rated'
    elif list_type == 'upcoming':
        movies = current_app.movieapi.get_upcoming(page)
        title = 'Upcoming'
    else:
        movies = []
        title = 'Error'

    context = {
        'movies': movies,
        'title': title,
        'page': page,
    }
    return render_template('main/movie_list.html', **context)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MovieApp</title>

    <link rel="stylesheet" href="/static/css/normalize.css">
    <link rel="stylesheet" href="/static/css/base.css">
    {% block header %}

    {% endblock %}
</head>

<body>
    <nav class="nav">
        <div class="nav-logo">
            <h1>MovieApp</h1>
        </div>
        <ul class="nav-links">
            <li><a href="{{ url_for('main.index') }}" class="active">Home</a></li>
            <li><a href="{{ url_for('main.movie_list', list_type='popular') }}">Popular</a></li>
            <li><a href="{{ url_for('main.movie_list', list_type='top_rated') }}">Top rated</a></li>
        </ul>
        <div class="nav-search">
            <input type="text" placeholder="SEARCH">
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" version="1" viewBox="0 0 48 48"
                enable-background="new 0 0 48 48" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
                <g fill="#616161">
                    <rect x="34.6" y="28.1" transform="matrix(.707 -.707 .707 .707 -15.154 36.586)" width="4"
                        height="17"></rect>
                    <circle cx="20" cy="20" r="16"></circle>
                </g>
                <rect x="36.2" y="32.1" transform="matrix(.707 -.707 .707 .707 -15.839 38.239)" fill="#37474F" width="4"
                    height="12.3"></rect>
                <circle fill="#64B5F6" cx="20" cy="20" r="13"></circle>
                <path fill="#BBDEFB"
                    d="M26.9,14.2c-1.7-2-4.2-3.2-6.9-3.2s-5.2,1.2-6.9,3.2c-0.4,0.4-0.3,1.1,0.1,1.4c0.4,0.4,1.1,0.3,1.4-0.1 C16,13.9,17.9,13,20,13s4,0.9,5.4,2.5c0.2,0.2,0.5,0.4,0.8,0.4c0.2,0,0.5-0.1,0.6-0.2C27.2,15.3,27.2,14.6,26.9,14.2z">
                </path>
            </svg>
        </div>
        <div class="nav-profile">
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 16 16" height="1.7em"
                width="1.7em" xmlns="http://www.w3.org/2000/svg">
                <path
                    d="M8 16a2 2 0 002-2H6a2 2 0 002 2zm.995-14.901a1 1 0 10-1.99 0A5.002 5.002 0 003 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z">
                </path>
            </svg>
            <img src="/static/images/avatar.png" alt="nav-avatar" class="nav-avatar">

            <button>
                <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" height="1em"
                    width="1em" xmlns="http://www.w3.org/2000/svg">
                    <path d="M13 16L18 12 13 8 13 11 4 11 4 13 13 13z"></path>
                    <path
                        d="M20,3h-9C9.897,3,9,3.897,9,5v4h2V5h9v14h-9v-4H9v4c0,1.103,0.897,2,2,2h9c1.103,0,2-0.897,2-2V5C22,3.897,21.103,3,20,3z">
                    </path>
                </svg>
                Login
            </button>
        </div>
    </nav>

    {% block content %}

    {% endblock %}
    <footer>
        <div>
            <h3>Navigation</h3>
            <ul>
                <li><a href="{{ url_for('main.index')}}">Home</a></li>
                <li><a href="{{ url_for('main.movie_list', list_type='popular') }}">Popular</a></li>
                <li><a href="{{ url_for('main.movie_list', list_type='top_rated') }}">Top rated</a></li>
            </ul>
        </div>

        <div>
            <h3>Talk to me</h3>
            <ul>
                <li><a href="/">nazariyznetyniak@gmail.com</a></li>
                <li><a href=""><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 496 512"
                            height="2em" width="2em" xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M248 8C111 8 0 119 0 256s111 248 248 248 248-111 248-248S385 8 248 8zm121.8 169.9l-40.7 191.8c-3 13.6-11.1 16.9-22.4 10.5l-62-45.7-29.9 28.8c-3.3 3.3-6.1 6.1-12.5 6.1l4.4-63.1 114.9-103.8c5-4.4-1.1-6.9-7.7-2.5l-142 89.4-61.2-19.1c-13.3-4.2-13.6-13.3 2.8-19.7l239.1-92.2c11.1-4 20.8 2.7 17.2 19.5z">
                            </path>
                        </svg></a></li>
            </ul>
        </div>

        <div>
            <h3>Follow me</h3>
            <ul>
                <li><a href="/"><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512"
                            height="1.2em" width="1.2em" xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M504 256C504 119 393 8 256 8S8 119 8 256c0 123.78 90.69 226.38 209.25 245V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.28c-30.8 0-40.41 19.12-40.41 38.73V256h68.78l-11 71.69h-57.78V501C413.31 482.38 504 379.78 504 256z">
                            </path>
                        </svg></a></li>
                <li><a href=""><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 1024 1024"
                            height="1.2em" width="1.2em" xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M512 378.7c-73.4 0-133.3 59.9-133.3 133.3S438.6 645.3 512 645.3 645.3 585.4 645.3 512 585.4 378.7 512 378.7zM911.8 512c0-55.2.5-109.9-2.6-165-3.1-64-17.7-120.8-64.5-167.6-46.9-46.9-103.6-61.4-167.6-64.5-55.2-3.1-109.9-2.6-165-2.6-55.2 0-109.9-.5-165 2.6-64 3.1-120.8 17.7-167.6 64.5C132.6 226.3 118.1 283 115 347c-3.1 55.2-2.6 109.9-2.6 165s-.5 109.9 2.6 165c3.1 64 17.7 120.8 64.5 167.6 46.9 46.9 103.6 61.4 167.6 64.5 55.2 3.1 109.9 2.6 165 2.6 55.2 0 109.9.5 165-2.6 64-3.1 120.8-17.7 167.6-64.5 46.9-46.9 61.4-103.6 64.5-167.6 3.2-55.1 2.6-109.8 2.6-165zM512 717.1c-113.5 0-205.1-91.6-205.1-205.1S398.5 306.9 512 306.9 717.1 398.5 717.1 512 625.5 717.1 512 717.1zm213.5-370.7c-26.5 0-47.9-21.4-47.9-47.9s21.4-47.9 47.9-47.9 47.9 21.4 47.9 47.9a47.84 47.84 0 0 1-47.9 47.9z">
                            </path>
                        </svg></a></li>
                <li><a href=""><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 1024 1024"
                            height="1.2em" width="1.2em" xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M880 112H144c-17.7 0-32 14.3-32 32v736c0 17.7 14.3 32 32 32h736c17.7 0 32-14.3 32-32V144c0-17.7-14.3-32-32-32zM349.3 793.7H230.6V411.9h118.7v381.8zm-59.3-434a68.8 68.8 0 1 1 68.8-68.8c-.1 38-30.9 68.8-68.8 68.8zm503.7 434H675.1V608c0-44.3-.8-101.2-61.7-101.2-61.7 0-71.2 48.2-71.2 98v188.9H423.7V411.9h113.8v52.2h1.6c15.8-30 54.5-61.7 112.3-61.7 120.2 0 142.3 79.1 142.3 181.9v209.4z">
                            </path>
                        </svg></a></li>
            </ul>
        </div>
    </footer>
</body>

</html>

app/templates/index.html
{% extends 'base.html' %}

{% block header %}
<link rel="stylesheet" href="/static/css/index.css">
<style>

{% for movie in upcoming %}
    .movie-background.movie-{{ movie.id }} {
        background: url("https://image.tmdb.org/t/p/original{{movie.get('backdrop_path')}}") no-repeat center ;
        background-size: cover;
    }
{% endfor %}
</style>
{% endblock %}

{% block content %}
<div class="center">
  <div class="carousel-wrapper">
    <!-- abstract radio buttons for slides -->
    {% for i in range(1, 11) %}
        <input id="slide{{ i }}" type="radio" name="controls" {% if i == 1 %}checked="checked"{% endif %} />
    {% endfor %}

    <!-- navigation dots -->
    {% for i in range(1, 11) %}
        <label for="slide{{ i }}" class="nav-dot"></label>
    {% endfor %}
    <!-- arrows -->
    {% for i in range(1, 11) %}
        <label for="slide{{ i }}" class="left-arrow"> &lt; </label>
    {% endfor %}
    {% for i in range(1, 11) %}
        <label for="slide{{ i }}" class="right-arrow"> > </label>
    {% endfor %}
    <div class="carousel">
      <ul>
        {% for movie in upcoming %}
        <li>
            <div class="movie-background movie-{{ movie.id }}">
                <div class="movie-descriprion">
                    <h2>{{movie.get('title')}}</h2>
                    <p>{{movie.get('overview')}}</p>
                    <a href="{{ url_for('main.movie_list', list_type='upcoming') }}" class="link">
                        More
                        <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" height="1.2em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M18 4l2 3h-3l-2-3h-2l2 3h-3l-2-3H8l2 3H7L5 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V4h-4zm-6.75 11.25L10 18l-1.25-2.75L6 14l2.75-1.25L10 10l1.25 2.75L14 14l-2.75 1.25zm5.69-3.31L16 14l-.94-2.06L13 11l2.06-.94L16 8l.94 2.06L19 11l-2.06.94z"></path></svg>
                    </a>
                </div>
                
            </div>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>

    

<div class="container">


    <!-- Now playing movielist -->
    <div class="movielist-header">
        <h2>Now playing</h2>
        <a class="link">
            See All 
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M20,3H4C2.897,3,2,3.897,2,5v6v8c0,1.103,0.897,2,2,2h16c1.103,0,2-0.897,2-2v-8V5C22,3.897,21.103,3,20,3z M20.001,9 C20,9,20,9,20.001,9h-0.466l-2.667-4H20L20.001,9z M9.535,9L6.868,5h2.597l2.667,4H9.535z M14.535,9l-2.667-4h2.597l2.667,4H14.535 z M4,5h0.465l2.667,4H4V5z M4,19v-8h16l0.002,8H4z"></path></svg>
        </a>
    </div>
    <div class="movielist">
        {% for movie in now_playing %}
        <a class="movie" href="{{ url_for('main.movie', movie_id=movie.get('id') ) }}">
            <img class="movie-main-image" src="https://image.tmdb.org/t/p/original{{movie.get('poster_path')}}" alt="">
            <h3 class="movie-title" title="{{movie.get('title')}}">{{movie.get('title')}}</h3>
            <p class="movie-date">{{movie.get('release_date')}}</p>
            <div class="movie-rate">
                <img src="/static/images/imdb.png" alt="">
                <p>{{movie.get('vote_average')}}</p>
                <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 1024 1024" height="1em"
                    width="1em" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M512.5 190.4l-94.4 191.3-211.2 30.7 152.8 149-36.1 210.3 188.9-99.3 188.9 99.2-36.1-210.3 152.8-148.9-211.2-30.7z">
                    </path>
                    <path
                        d="M908.6 352.8l-253.9-36.9L541.2 85.8c-3.1-6.3-8.2-11.4-14.5-14.5-15.8-7.8-35-1.3-42.9 14.5L370.3 315.9l-253.9 36.9c-7 1-13.4 4.3-18.3 9.3a32.05 32.05 0 0 0 .6 45.3l183.7 179.1L239 839.4a31.95 31.95 0 0 0 46.4 33.7l227.1-119.4 227.1 119.4c6.2 3.3 13.4 4.4 20.3 3.2 17.4-3 29.1-19.5 26.1-36.9l-43.4-252.9 183.7-179.1c5-4.9 8.3-11.3 9.3-18.3 2.7-17.5-9.5-33.7-27-36.3zM665.3 561.3l36.1 210.3-188.9-99.2-188.9 99.3 36.1-210.3-152.8-149 211.2-30.7 94.4-191.3 94.4 191.3 211.2 30.7-152.8 148.9z">
                    </path>
                </svg>
            </div>
        </a>
        {% endfor %}
        <a href="{{ url_for('main.movie_list', list_type='now_playing') }}" class="next-link">
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" height="3em" width="3em"
                xmlns="http://www.w3.org/2000/svg">
                <polygon fill="white" stroke="#000" stroke-width="2" points="6 2 18 12 6 22"></polygon>
            </svg>
        </a>
    </div>


    <!-- Popular movielist -->
    <div class="movielist-header">
        <h2>Popular</h2>
        <a class="link">
            See All 
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M20,3H4C2.897,3,2,3.897,2,5v6v8c0,1.103,0.897,2,2,2h16c1.103,0,2-0.897,2-2v-8V5C22,3.897,21.103,3,20,3z M20.001,9 C20,9,20,9,20.001,9h-0.466l-2.667-4H20L20.001,9z M9.535,9L6.868,5h2.597l2.667,4H9.535z M14.535,9l-2.667-4h2.597l2.667,4H14.535 z M4,5h0.465l2.667,4H4V5z M4,19v-8h16l0.002,8H4z"></path></svg>
        </a>
    </div>
    <div class="movielist">
        {% for movie in popular %}
        <a class="movie" href="{{ url_for('main.movie', movie_id=movie.get('id') ) }}">
            <img class="movie-main-image" src="https://image.tmdb.org/t/p/original{{movie.get('poster_path')}}" alt="">
            <h3 class="movie-title" title="{{movie.get('title')}}">{{movie.get('title')}}</h3>
            <p class="movie-date">{{movie.get('release_date')}}</p>
            <div class="movie-rate">
                <img src="/static/images/imdb.png" alt="">
                <p>{{movie.get('vote_average')}}</p>
                <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 1024 1024" height="1em"
                    width="1em" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M512.5 190.4l-94.4 191.3-211.2 30.7 152.8 149-36.1 210.3 188.9-99.3 188.9 99.2-36.1-210.3 152.8-148.9-211.2-30.7z">
                    </path>
                    <path
                        d="M908.6 352.8l-253.9-36.9L541.2 85.8c-3.1-6.3-8.2-11.4-14.5-14.5-15.8-7.8-35-1.3-42.9 14.5L370.3 315.9l-253.9 36.9c-7 1-13.4 4.3-18.3 9.3a32.05 32.05 0 0 0 .6 45.3l183.7 179.1L239 839.4a31.95 31.95 0 0 0 46.4 33.7l227.1-119.4 227.1 119.4c6.2 3.3 13.4 4.4 20.3 3.2 17.4-3 29.1-19.5 26.1-36.9l-43.4-252.9 183.7-179.1c5-4.9 8.3-11.3 9.3-18.3 2.7-17.5-9.5-33.7-27-36.3zM665.3 561.3l36.1 210.3-188.9-99.2-188.9 99.3 36.1-210.3-152.8-149 211.2-30.7 94.4-191.3 94.4 191.3 211.2 30.7-152.8 148.9z">
                    </path>
                </svg>
            </div>
        </a>
        {% endfor %}
        <a href="{{ url_for('main.movie_list', list_type='popular') }}" class="next-link">
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" height="3em" width="3em"
                xmlns="http://www.w3.org/2000/svg">
                <polygon fill="white" stroke="#000" stroke-width="2" points="6 2 18 12 6 22"></polygon>
            </svg>
        </a>
    </div>

    <!-- Top rated -->

    <div class="movielist-header">
        <h2>Top Rated</h2>
        <a class="link">
            See All 
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M20,3H4C2.897,3,2,3.897,2,5v6v8c0,1.103,0.897,2,2,2h16c1.103,0,2-0.897,2-2v-8V5C22,3.897,21.103,3,20,3z M20.001,9 C20,9,20,9,20.001,9h-0.466l-2.667-4H20L20.001,9z M9.535,9L6.868,5h2.597l2.667,4H9.535z M14.535,9l-2.667-4h2.597l2.667,4H14.535 z M4,5h0.465l2.667,4H4V5z M4,19v-8h16l0.002,8H4z"></path></svg>
        </a>
    </div>
    <div class="movielist">
        {% for movie in top_rated %}
        <a class="movie" href="{{ url_for('main.movie', movie_id=movie.get('id') ) }}">
            <img class="movie-main-image" src="https://image.tmdb.org/t/p/original{{movie.get('poster_path')}}" alt="">
            <h3 class="movie-title" title="{{movie.get('title')}}">{{movie.get('title')}}</h3>
            <p class="movie-date">{{movie.get('release_date')}}</p>
            <div class="movie-rate">
                <img src="/static/images/imdb.png" alt="">
                <p>{{movie.get('vote_average')}}</p>
                <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 1024 1024" height="1em"
                    width="1em" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M512.5 190.4l-94.4 191.3-211.2 30.7 152.8 149-36.1 210.3 188.9-99.3 188.9 99.2-36.1-210.3 152.8-148.9-211.2-30.7z">
                    </path>
                    <path
                        d="M908.6 352.8l-253.9-36.9L541.2 85.8c-3.1-6.3-8.2-11.4-14.5-14.5-15.8-7.8-35-1.3-42.9 14.5L370.3 315.9l-253.9 36.9c-7 1-13.4 4.3-18.3 9.3a32.05 32.05 0 0 0 .6 45.3l183.7 179.1L239 839.4a31.95 31.95 0 0 0 46.4 33.7l227.1-119.4 227.1 119.4c6.2 3.3 13.4 4.4 20.3 3.2 17.4-3 29.1-19.5 26.1-36.9l-43.4-252.9 183.7-179.1c5-4.9 8.3-11.3 9.3-18.3 2.7-17.5-9.5-33.7-27-36.3zM665.3 561.3l36.1 210.3-188.9-99.2-188.9 99.3 36.1-210.3-152.8-149 211.2-30.7 94.4-191.3 94.4 191.3 211.2 30.7-152.8 148.9z">
                    </path>
                </svg>
            </div>
        </a>
        {% endfor %}
        <a href="{{ url_for('main.movie_list', list_type='top_rated') }}" class="next-link">
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" height="3em" width="3em"
                xmlns="http://www.w3.org/2000/svg">
                <polygon fill="white" stroke="#000" stroke-width="2" points="6 2 18 12 6 22"></polygon>
            </svg>
        </a>
    </div>

</div>

{% endblock %}

app/templates/main/movie_list.html
{% extends 'base.html' %}

{% block header %}
    <link rel="stylesheet" href="/static/css/movie_list.css">
{% endblock %}

{% block content %}
    
<div class="container">
    <!-- Now playing movielist -->
    <div class="movielist-header">
        <h2>{{title}}</h2>
    </div>
    <div class="movielist">
        {% for movie in movies %}
        <a class="movie" href="{{ url_for('main.movie', movie_id=movie.get('id') ) }}">
            <img class="movie-main-image" src="https://image.tmdb.org/t/p/original{{movie.get('poster_path')}}" alt="">
            <h3 class="movie-title" title="{{movie.get('title')}}">{{movie.get('title')}}</h3>
            <p class="movie-date">{{movie.get('release_date')}}</p>
            <div class="movie-rate">
                <img src="/static/images/imdb.png" alt="">
                <p>{{movie.get('vote_average')}}</p>
                <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 1024 1024" height="1em"
                    width="1em" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M512.5 190.4l-94.4 191.3-211.2 30.7 152.8 149-36.1 210.3 188.9-99.3 188.9 99.2-36.1-210.3 152.8-148.9-211.2-30.7z">
                    </path>
                    <path
                        d="M908.6 352.8l-253.9-36.9L541.2 85.8c-3.1-6.3-8.2-11.4-14.5-14.5-15.8-7.8-35-1.3-42.9 14.5L370.3 315.9l-253.9 36.9c-7 1-13.4 4.3-18.3 9.3a32.05 32.05 0 0 0 .6 45.3l183.7 179.1L239 839.4a31.95 31.95 0 0 0 46.4 33.7l227.1-119.4 227.1 119.4c6.2 3.3 13.4 4.4 20.3 3.2 17.4-3 29.1-19.5 26.1-36.9l-43.4-252.9 183.7-179.1c5-4.9 8.3-11.3 9.3-18.3 2.7-17.5-9.5-33.7-27-36.3zM665.3 561.3l36.1 210.3-188.9-99.2-188.9 99.3 36.1-210.3-152.8-149 211.2-30.7 94.4-191.3 94.4 191.3 211.2 30.7-152.8 148.9z">
                    </path>
                </svg>
            </div>
        </a>
        {% endfor %}
    </div>

    <div class="pages">
        {% for i in range(1,11) %}
            <a href="?page={{i}}" {% if page==i %} class="active" {% endif %}>{{i}}</a>
        {% endfor %}
    </div>


</div>
{% endblock %}